### PR TITLE
[Fix] Fix the punctuation display problem and the path separator problem on Windows

### PR DESCRIPTION
**Pull request by RangeKing**
Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.

## Motivation

1.Fix the punctuation display problem on Windows, when running the command `mim run mmdet -h`.

10615f6753552529333432d391461b5
2.Fix the path separator problem on Windows, when running the command `mim run mmdet -h`.

## Modification
Replace all `Don’t` -> `Don\'t` for problem 1.
In `mim/click/customcommand.py`, '/' -> os.sep for problem 2.

### CODE REVIEW

**Comment by ice-tong** [comment]
Hi @RangeKing , thanks for your kind contribution~

I haven't reproduced this display problem in both CMD and Powershell.
Can you provide more information to help me reproduce this problem? ^_^

**Comment by RangeKing** [comment]
image
@ice-tong It also occurs in CMD which uses a different font from Powershell.

Here's my env info:
```
Name: openmim
Version: 0.3.2
```
```
sys.platform: win32
Python: 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
numpy_random_seed: 2147483648
GPU 0: NVIDIA GeForce RTX 2070
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1
NVCC: Cuda compilation tools, release 10.1, V10.1.16
GCC: n/a
PyTorch: 1.8.1+cu101
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829913
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 2019
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.4
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.1, CUDNN_VERSION=7.6.4, CXX_COMPILER=C:/w/b/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -DNDEBUG -DUSE_FBGEMM -DUSE_XNNPACK, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, 
USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON,

TorchVision: 0.9.1+cu101
OpenCV: 4.6.0
MMEngine: 0.2.0
MMCV: 2.0.0rc1
MMDetection: 3.0.0rc1
MMYOLO: 0.1.1+5153d05
```

**Comment by ice-tong** [comment]
Hi @RangeKing, thanks for the information~

I have not successfully reproduced this problem, but I believe it is an enhancement that does not affect compatibility. 

This change looks great to me, and you should rebase the main master to fix the pre-commit error in CI. ^_^

**Comment by ice-tong** [comment]
Hi @RangeKing , the rebase seems not successful.

image

Maybe the following steps work:
```python
git add remote mim https://github.com/open-mmlab/mim.git
git pull mim main:main
git rebase main
git push -f origin fix_typo:fix_typo
```

**Comment by RangeKing** [comment]
@ice-tong Thank you for your patient guidance. The rebase had been successful.
image

**Review by zhouzaida — APPROVED** [review]

**Review by ice-tong — APPROVED** [review]
LGTM

**Pull request merged**
