### PR TITLE
Fix mmaction2 package name and run script

### PR DESCRIPTION
**Pull request by yeliudev**

### CODE REVIEW

**Comment by zhouzaida** [comment]
Hi @yeliudev , sorry for my late reply. Could you merge the upstream branch to fix the CI?

**Comment by yeliudev** [comment]
> Hi @yeliudev , sorry for my late reply. Could you merge the upstream branch to fix the CI?

Done. Thanks for your reply!

**Comment by zhouzaida** [comment]
We also need to modify the following lines.

https://github.com/open-mmlab/mim/blob/945a565ba4fe7b263ac1102c57944d9d4d9b676b/mim/click/customcommand.py#L61

https://github.com/open-mmlab/mim/blob/945a565ba4fe7b263ac1102c57944d9d4d9b676b/mim/click/customcommand.py#L101

**Comment by yeliudev** [comment]
> We also need to modify the following lines.
> 
> https://github.com/open-mmlab/mim/blob/945a565ba4fe7b263ac1102c57944d9d4d9b676b/mim/click/customcommand.py#L61
> 
> https://github.com/open-mmlab/mim/blob/945a565ba4fe7b263ac1102c57944d9d4d9b676b/mim/click/customcommand.py#L101

Updated.

**Review by ice-tong — APPROVED** [review]
LGTM

**Review by zhouzaida — APPROVED** [review]

**Pull request merged**
